pipeline {
    agent any

    stages {

        stage('Run Tests') {
            steps {
                echo 'Checking Python...'
                bat 'where python'
                bat 'python --version'

                echo 'Installing pytest...'
                bat 'python -m pip install pytest'

                echo 'Running tests...'
                bat 'python -m pytest test_addition.py'
            }
        }

        stage('Run Scripts') {
            steps {
                echo 'Running hello.py...'
                bat 'python hello.py'

                echo 'Running addition.py...'
                bat 'python addition.py'
            }
        }

        stage('Cleanup') {
            steps {
                echo 'Cleaning up...'
            }
        }
    }
}