pipeline {
    agent any

    stages {

        stage('Run Tests') {
            steps {
                echo 'Running Python tests...'

                bat '"C:\\Users\\Shabana\\AppData\\Local\\Programs\\Python\\Python37\\python.exe" -m pip install pytest'

                bat '"C:\\Users\\Shabana\\AppData\\Local\\Programs\\Python\\Python37\\python.exe" -m pytest pythonbasics\\test_addition.py'
            }
        }

        stage('Run Scripts') {
            steps {
                echo 'Running Python programs...'

                bat '"C:\\Users\\Shabana\\AppData\\Local\\Programs\\Python\\Python37\\python.exe" pythonbasics\\hello.py'

                bat '"C:\\Users\\Shabana\\AppData\\Local\\Programs\\Python\\Python37\\python.exe" pythonbasics\\addition.py'
            }
        }

        stage('Cleanup') {
            steps {
                echo 'Cleaning up...'
            }
        }
    }
}