pipeline {
    agent any

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Clone Repo') {
            steps {
                echo 'Cloning repository...'
            }
        }

        stage('Run Tests') {
            steps {
                echo 'Running Pytest tests...'
                bat 'python -m pytest pythonbasics/test_addition.py'
            }
        }

        stage('Run Scripts') {
            steps {
                echo 'Executing Python scripts...'
                bat 'python pythonbasics/hello.py'
                bat 'python pythonbasics/addition.py'
            }
        }

        stage('Cleanup') {
            steps {
                echo 'Cleaning up temporary files...'
            }
        }
    }
}